security:
  password_hashers:
    AppBundle\Entity\User:
      algorithm: bcrypt

  providers:
    doctrine:
      entity:
        class: AppBundle\Entity\User
        property: username

  firewalls:
    main:
      lazy: true
      pattern: ^/

      form_login:
        login_path: login
        check_path: /login
        enable_csrf: true
        csrf_token_id: authenticate

      logout:
        path: logout
        target: /

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/users, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: ROLE_USER }
